import { asc, eq } from "drizzle-orm";
import { getDb } from "@/db";
import { productItems, productOptions } from "@/db/schema";
import { requireAdmin } from "@/lib/admin-auth";
export async function GET(request:Request){try{await requireAdmin();const category=new URL(request.url).searchParams.get("category")||"metal";const [items,options]=await Promise.all([getDb().select().from(productItems).where(eq(productItems.category,category)).orderBy(asc(productItems.sortOrder),asc(productItems.id)),getDb().select().from(productOptions).where(eq(productOptions.category,category)).orderBy(asc(productOptions.sortOrder),asc(productOptions.id))]);return Response.json({items,options})}catch{return Response.json({error:"Unauthorized"},{status:401})}}
export async function POST(request:Request){try{await requireAdmin();const p=await request.json() as Record<string,unknown>;const now=new Date().toISOString(),galleryKeys=normalizeGallery(p.galleryKeys);if(p.recordType==="option"){if(!p.category||!p.optionType||!p.titleEn||!p.titleTr)return Response.json({error:"Zorunlu alanları doldurun."},{status:400});const productItemIds=normalizeIds(p.productItemIds,p.productItemId);if(p.optionType==="finish"&&productItemIds==="[]")return Response.json({error:"Bitirme şekli için en az bir mevcut tip seçin."},{status:400});const firstId=(JSON.parse(productItemIds) as number[])[0]||null;const values={category:String(p.category),optionType:String(p.optionType),productItemId:firstId,productItemIds,titleEn:String(p.titleEn),titleTr:String(p.titleTr),bodyEn:String(p.bodyEn||""),bodyTr:String(p.bodyTr||""),imageKey:p.imageKey?String(p.imageKey):null,galleryKeys,sortOrder:Number(p.sortOrder||0),updatedAt:now};if(p.id){await getDb().update(productOptions).set(values).where(eq(productOptions.id,Number(p.id)));return Response.json({ok:true,id:Number(p.id)})}const [row]=await getDb().insert(productOptions).values(values).returning({id:productOptions.id});return Response.json({ok:true,id:row.id})}if(!p.category||!p.titleEn||!p.titleTr)return Response.json({error:"Ürün başlıklarını doldurun."},{status:400});const values={category:String(p.category),titleEn:String(p.titleEn),titleTr:String(p.titleTr),overviewEn:String(p.overviewEn||""),overviewTr:String(p.overviewTr||""),featuresEn:String(p.featuresEn||""),featuresTr:String(p.featuresTr||""),usesEn:String(p.usesEn||""),usesTr:String(p.usesTr||""),imageKey:p.imageKey?String(p.imageKey):null,galleryKeys,sortOrder:Number(p.sortOrder||0),updatedAt:now};if(p.id){await getDb().update(productItems).set(values).where(eq(productItems.id,Number(p.id)));return Response.json({ok:true,id:Number(p.id)})}const [row]=await getDb().insert(productItems).values(values).returning({id:productItems.id});return Response.json({ok:true,id:row.id})}catch(e){return Response.json({error:e instanceof Error&&e.message==="UNAUTHORIZED"?"Unauthorized":"Kayıt kaydedilemedi."},{status:e instanceof Error&&e.message==="UNAUTHORIZED"?401:500})}}
function normalizeGallery(value:unknown){try{const parsed=Array.isArray(value)?value:JSON.parse(String(value||"[]"));return JSON.stringify(parsed.filter((key:unknown)=>typeof key==="string"&&key).slice(0,30))}catch{return "[]"}}
function normalizeIds(value:unknown,legacy:unknown){try{const parsed=Array.isArray(value)?value:JSON.parse(String(value||"[]"));const ids=parsed.map(Number).filter(Number.isInteger);if(!ids.length&&legacy)ids.push(Number(legacy));return JSON.stringify([...new Set(ids)])}catch{return legacy?JSON.stringify([Number(legacy)]):"[]"}}
export async function DELETE(request:Request){try{await requireAdmin();const u=new URL(request.url),id=Number(u.searchParams.get("id")),type=u.searchParams.get("type");if(!id)return Response.json({error:"Invalid id"},{status:400});if(type==="option")await getDb().delete(productOptions).where(eq(productOptions.id,id));else await getDb().delete(productItems).where(eq(productItems.id,id));return Response.json({ok:true})}catch{return Response.json({error:"Kayıt silinemedi."},{status:500})}}
