"use client";
import { useEffect,useState } from "react";
import { BookOpen,Box,FileText,ImagePlus,LogOut,Save,Settings,ShieldCheck,Users } from "lucide-react";

type Section={key:string;titleEn:string;titleTr:string;bodyEn:string;bodyTr:string;imageKey?:string|null};
type Post={id?:number;titleEn:string;titleTr:string;excerptEn:string;excerptTr:string;contentEn:string;contentTr:string;imageKey?:string|null;published:boolean};
type User={id:number;firstName:string;lastName:string;email:string;active:boolean};
const corporate:Record<string,string>={history:"Tarihçe",vision:"Vizyon",mission:"Misyon",kvkk:"KVKK",references:"Referans Markalarımız"};
const product:Record<string,string>={product_metal:"Metal Fermuar",product_nylon:"Naylon Fermuar",product_molded:"Kemik Fermuar"};
const quality:Record<string,string>={quality_policy:"Kalite Politikası",quality_certificates:"Kalite Belgeleri",quality_testing:"Fermuar Test Yöntemleri",quality_standards:"Ölçme Standartları"};
const blankPost:Post={titleEn:"",titleTr:"",excerptEn:"",excerptTr:"",contentEn:"",contentTr:"",imageKey:null,published:true};
const blankSection=(key:string):Section=>({key,titleEn:"",titleTr:"",bodyEn:"",bodyTr:"",imageKey:null});
const productFields=["general","features","coatings","uses"] as const;
const productLabels={general:"Genel Açıklama",features:"Özellikler",coatings:"Kaplamalar",uses:"Kullanım Alanları"};
const parseBody=(v:string)=>{try{return JSON.parse(v||"{}")}catch{return{general:v}}};

export default function AdminPanel(){
 const [auth,setAuth]=useState<boolean|null>(null),[mode,setMode]=useState<"login"|"forgot"|"reset">("login"),[error,setError]=useState(""),[tab,setTab]=useState("content"),[notice,setNotice]=useState("");
 const [sections,setSections]=useState<Record<string,Section>>({}),[selected,setSelected]=useState("history"),[posts,setPosts]=useState<Post[]>([]),[post,setPost]=useState<Post>(blankPost),[users,setUsers]=useState<User[]>([]),[settings,setSettings]=useState<Record<string,string>>({});
 useEffect(()=>{const reset=new URLSearchParams(location.search).get("reset");if(reset)setMode("reset");fetch("/api/admin/login").then(r=>r.json()).then(d=>{setAuth(d.authenticated);if(d.authenticated)load()}).catch(()=>setAuth(false))},[]);
 async function load(){const [c,b,u,s]=await Promise.all([fetch("/api/admin/content").then(r=>r.json()),fetch("/api/admin/blog").then(r=>r.json()),fetch("/api/admin/users").then(r=>r.json()),fetch("/api/admin/settings").then(r=>r.json())]);const map:Record<string,Section>={};for(const key of Object.keys({...corporate,...product,...quality})){map[key]=c.sections?.find((x:Section)=>x.key===key)??blankSection(key)}setSections(map);setPosts(b.posts??[]);setUsers(u.users??[]);setSettings(s.settings??{})}
 async function login(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const r=await fetch("/api/admin/login",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({username:f.get("username"),password:f.get("password")})});if(!r.ok){setError("Kullanıcı adı/e-posta veya şifre hatalı.");return}setAuth(true);setError("");await load()}
 async function forgot(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const d=await fetch("/api/admin/forgot-password",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({email:f.get("email")})}).then(r=>r.json());setError(d.message)}
 async function reset(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),password=String(f.get("password")),again=String(f.get("again"));if(password!==again){setError("Şifreler eşleşmiyor.");return}const r=await fetch("/api/admin/reset-password",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({token:new URLSearchParams(location.search).get("reset"),password})});const d=await r.json();if(!r.ok){setError(d.error);return}history.replaceState({},"","/adminpanel");setMode("login");setError("Şifreniz yenilendi. Giriş yapabilirsiniz.")}
 async function logout(){await fetch("/api/admin/logout",{method:"POST"});setAuth(false)}
 async function upload(file:File,target:"section"|"gallery"|"post"|"logo"){const f=new FormData();f.append("file",file);const r=await fetch("/api/admin/upload",{method:"POST",body:f}),d=await r.json();if(!r.ok){setNotice(d.error);return}if(target==="section")setSections(s=>({...s,[selected]:{...s[selected],imageKey:d.key}}));else if(target==="gallery")setSections(s=>{const item=s[selected],en=parseBody(item.bodyEn);return{...s,[selected]:{...item,bodyEn:JSON.stringify({...en,gallery:[...(en.gallery||[]),d.key]})}}});else if(target==="post")setPost(p=>({...p,imageKey:d.key}));else setSettings(s=>({...s,logoKey:d.key}));setNotice("Görsel yüklendi; değişiklikleri kaydedin.")}
 async function saveSection(){const r=await fetch("/api/admin/content",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify(sections[selected])});setNotice(r.ok?"İçerik kaydedildi.":"İçerik kaydedilemedi.")}
 function removeGallery(key:string){setSections(state=>{const item=state[selected],en=parseBody(item.bodyEn);return{...state,[selected]:{...item,bodyEn:JSON.stringify({...en,gallery:(en.gallery||[]).filter((x:string)=>x!==key)})}}})}
 async function savePost(){const r=await fetch("/api/admin/blog",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(post)});if(r.ok){setNotice("Blog yazısı kaydedildi.");setPost(blankPost);await load()}}
 async function removePost(id?:number){if(id){await fetch(`/api/admin/blog?id=${id}`,{method:"DELETE"});await load()}}
 async function createUser(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget));const r=await fetch("/api/admin/users",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(f)}),d=await r.json();setNotice(r.ok?"Kullanıcı oluşturuldu.":d.error);if(r.ok){e.currentTarget.reset();await load()}}
 async function removeUser(id:number){await fetch(`/api/admin/users?id=${id}`,{method:"DELETE"});await load()}
 async function saveSettings(){const r=await fetch("/api/admin/settings",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify(settings)});setNotice(r.ok?"Ayarlar kaydedildi.":"Ayarlar kaydedilemedi.")}
 if(auth===null)return <div className="cms-loading">Yönetim paneli yükleniyor…</div>;
 if(!auth)return <main className="cms-login"><form onSubmit={mode==="login"?login:mode==="forgot"?forgot:reset}><Brand/><small>YÖNETİM PANELİ</small><h1>{mode==="login"?"Tekrar hoş geldiniz":mode==="forgot"?"Şifremi unuttum":"Yeni şifre oluştur"}</h1>{mode==="login"?<><label><span>Kullanıcı adı veya e-posta</span><input name="username" defaultValue="admin" required/></label><label><span>Şifre</span><input name="password" type="password" defaultValue="admin" required/></label></>:mode==="forgot"?<label><span>E-posta</span><input name="email" type="email" required/></label>:<><label><span>Yeni şifre</span><input name="password" type="password" minLength={8} required/></label><label><span>Yeni şifre tekrar</span><input name="again" type="password" minLength={8} required/></label></>}{error&&<div className="cms-error">{error}</div>}<button type="submit">{mode==="login"?"GİRİŞ YAP":mode==="forgot"?"BAĞLANTI GÖNDER":"ŞİFREYİ YENİLE"}</button>{mode!=="login"?<button type="button" className="cms-link" onClick={()=>setMode("login")}>Giriş ekranına dön</button>:<button type="button" className="cms-link" onClick={()=>setMode("forgot")}>Şifremi unuttum</button>}<a href="/">← Siteye dön</a></form></main>;
 const groups=tab==="content"?corporate:tab==="products"?product:quality,current=sections[selected];
 return <div className="cms"><aside><Brand/><p>İçerik Yönetimi</p>{[["content","Kurumsal İçerikler",FileText],["products","Ürünler",Box],["quality","Kalite",ShieldCheck],["blog","Blog",BookOpen],["users","Kullanıcılar",Users],["settings","Ayarlar",Settings]].map(([id,label,Icon]:any)=><button key={id} className={tab===id?"active":""} onClick={()=>{setTab(id);if(id==="content")setSelected("history");if(id==="products")setSelected("product_metal");if(id==="quality")setSelected("quality_policy")}}><Icon/>{label}</button>)}<button className="cms-logout" onClick={logout}><LogOut/>Çıkış yap</button></aside><main><header><div><small>ECEX CMS</small><h1>{({content:"Kurumsal İçerikler",products:"Ürün Yönetimi",quality:"Kalite Yönetimi",blog:"Blog Yönetimi",users:"Kullanıcılar",settings:"Ayarlar"} as any)[tab]}</h1></div>{notice&&<output>{notice}</output>}</header>
 {(["content","products","quality"].includes(tab)&&current)&&<><div className="cms-tabs">{Object.entries(groups).map(([key,name])=><button className={selected===key?"active":""} key={key} onClick={()=>setSelected(key)}>{name}</button>)}</div><section className="cms-editor"><LanguageEditor lang="en" current={current} productMode={tab==="products"} setSection={patch=>setSections(s=>({...s,[selected]:{...s[selected],...patch}}))}/><LanguageEditor lang="tr" current={current} productMode={tab==="products"} setSection={patch=>setSections(s=>({...s,[selected]:{...s[selected],...patch}}))}/><Media value={current.imageKey} onFile={f=>upload(f,"section")} label={tab==="products"?"Ana ürün görseli":"Sayfa görseli"}/>{tab==="products"&&<GalleryEditor keys={parseBody(current.bodyEn).gallery||[]} onFile={f=>upload(f,"gallery")} onRemove={removeGallery}/>}<button className="cms-save" onClick={saveSection}><Save/>DEĞİŞİKLİKLERİ KAYDET</button></section></>}
 {tab==="blog"&&<div className="cms-blog"><section className="cms-editor"><PostEditor lang="en" post={post} setPost={setPost}/><PostEditor lang="tr" post={post} setPost={setPost}/><Media value={post.imageKey} onFile={f=>upload(f,"post")} label="Kapak görseli"/><label className="cms-check"><input type="checkbox" checked={post.published} onChange={e=>setPost(p=>({...p,published:e.target.checked}))}/> Yayında</label><button className="cms-save" onClick={savePost}><Save/>YAZIYI KAYDET</button></section><section className="cms-posts"><h2>Yazılar</h2>{posts.map(p=><article key={p.id}><div><small>{p.published?"YAYINDA":"TASLAK"}</small><h3>{p.titleTr}</h3></div><button onClick={()=>setPost(p)}>Düzenle</button><button onClick={()=>removePost(p.id)}>Sil</button></article>)}</section></div>}
 {tab==="users"&&<div className="cms-settings-grid"><form className="cms-card" onSubmit={createUser}><h2>Yeni kullanıcı</h2><div className="form-row"><Field name="firstName" label="İsim"/><Field name="lastName" label="Soyisim"/></div><Field name="email" label="E-posta" type="email"/><Field name="password" label="Şifre (en az 8 karakter)" type="password" minLength={8}/><button className="cms-save" type="submit">KULLANICI OLUŞTUR</button></form><section className="cms-card"><h2>Kullanıcılar</h2><article className="cms-user"><div><strong>Varsayılan Admin</strong><span>admin kullanıcı adı ile giriş</span></div><em>SİSTEM</em></article>{users.map(u=><article className="cms-user" key={u.id}><div><strong>{u.firstName} {u.lastName}</strong><span>{u.email}</span></div><button onClick={()=>removeUser(u.id)}>Sil</button></article>)}</section></div>}
 {tab==="settings"&&<div className="cms-settings-grid"><section className="cms-card"><h2>Site logosu</h2><p>Yüklenen logo, site ve yönetim panelindeki tüm logo alanlarında kullanılır.</p><Media value={settings.logoKey} onFile={f=>upload(f,"logo")} label="Logo yükle"/></section><section className="cms-card"><h2>SMTP ayarları</h2><div className="form-row"><Field label="SMTP sunucusu" value={settings.smtpHost} onChange={v=>setSettings(s=>({...s,smtpHost:v}))}/><Field label="Port" value={settings.smtpPort||"587"} onChange={v=>setSettings(s=>({...s,smtpPort:v}))}/></div><Field label="Kullanıcı adı" value={settings.smtpUser} onChange={v=>setSettings(s=>({...s,smtpUser:v}))}/><Field label="Şifre" type="password" value={settings.smtpPassword} onChange={v=>setSettings(s=>({...s,smtpPassword:v}))}/><div className="form-row"><Field label="Gönderen adı" value={settings.smtpFromName||"ECEX"} onChange={v=>setSettings(s=>({...s,smtpFromName:v}))}/><Field label="Gönderen e-posta" type="email" value={settings.smtpFromEmail} onChange={v=>setSettings(s=>({...s,smtpFromEmail:v}))}/></div><Field label="HTTPS SMTP geçidi URL'si" value={settings.smtpGatewayUrl} onChange={v=>setSettings(s=>({...s,smtpGatewayUrl:v}))}/><label className="cms-check"><input type="checkbox" checked={settings.smtpSecure==="true"} onChange={e=>setSettings(s=>({...s,smtpSecure:String(e.target.checked)}))}/> Güvenli bağlantı (SSL/TLS)</label><p className="cms-note">Şifre yenileme e-postaları, barındırma ortamıyla uyumlu HTTPS SMTP geçidi üzerinden gönderilir.</p></section><button className="cms-save" onClick={saveSettings}><Save/>AYARLARI KAYDET</button></div>}
 </main></div>
}

function Brand(){const[logo,setLogo]=useState("");useEffect(()=>{fetch("/api/settings").then(r=>r.json()).then(d=>setLogo(d.settings?.logoKey||""))},[]);return <div className="cms-brand">{logo?<img className="cms-logo-img" src={`/api/media/${logo}`} alt="ECEX"/>:<><span className="logo-mark"><i/><b/></span><strong>ECEX</strong></>}</div>}
function Field({label,name,type="text",value,onChange,minLength}:{label:string,name?:string,type?:string,value?:string,onChange?:(v:string)=>void;minLength?:number}){return <label className="cms-field"><span>{label}</span><input name={name} type={type} value={onChange?value:undefined} onChange={e=>onChange?.(e.target.value)} minLength={minLength} required/></label>}
function Media({value,onFile,label}:{value?:string|null;onFile:(f:File)=>void;label:string}){return <div className="cms-media"><ImagePlus/><div><strong>{label}</strong><span>JPG, PNG, WEBP veya SVG · En fazla 5 MB</span></div><input type="file" accept="image/*" onChange={e=>e.target.files?.[0]&&onFile(e.target.files[0])}/>{value&&<img src={`/api/media/${value}`} alt="Yüklenen görsel"/>}</div>}
function GalleryEditor({keys,onFile,onRemove}:{keys:string[];onFile:(f:File)=>void;onRemove:(key:string)=>void}){return <div className="cms-gallery-edit"><div><strong>Ürün galeri görselleri</strong><span>Referans tasarımdaki küçük görsel şeridinde gösterilir.</span></div><input type="file" accept="image/*" onChange={e=>e.target.files?.[0]&&onFile(e.target.files[0])}/><div>{keys.map(key=><figure key={key}><img src={`/api/media/${key}`} alt=""/><button onClick={()=>onRemove(key)} type="button">Sil</button></figure>)}</div></div>}
function LanguageEditor({lang,current,productMode,setSection}:{lang:"en"|"tr";current:Section;productMode:boolean;setSection:(p:Partial<Section>)=>void}){const titleKey=lang==="en"?"titleEn":"titleTr",bodyKey=lang==="en"?"bodyEn":"bodyTr",data=parseBody(current[bodyKey]);return <div className="cms-language"><h2>{lang==="en"?"🇬🇧 English":"🇹🇷 Türkçe"}</h2><label><span>Başlık</span><input value={current[titleKey]} onChange={e=>setSection({[titleKey]:e.target.value})}/></label>{productMode?productFields.map(key=><label key={key}><span>{productLabels[key]}</span><textarea rows={key==="general"?7:4} value={data[key]||""} onChange={e=>setSection({[bodyKey]:JSON.stringify({...data,[key]:e.target.value})})}/></label>):<label><span>İçerik</span><textarea rows={15} value={current[bodyKey]} onChange={e=>setSection({[bodyKey]:e.target.value})}/></label>}</div>}
function PostEditor({lang,post,setPost}:{lang:"en"|"tr";post:Post;setPost:React.Dispatch<React.SetStateAction<Post>>}){const s=lang==="en"?"En":"Tr";return <div className="cms-language"><h2>{lang==="en"?"🇬🇧 English":"🇹🇷 Türkçe"}</h2>{[["title","Başlık",2],["excerpt","Kısa açıklama",3],["content","İçerik",10]].map(([key,label,rows]:any)=><label key={key}><span>{label}</span>{rows===2?<input value={(post as any)[key+s]} onChange={e=>setPost(p=>({...p,[key+s]:e.target.value}))}/>:<textarea rows={rows} value={(post as any)[key+s]} onChange={e=>setPost(p=>({...p,[key+s]:e.target.value}))}/>}</label>)}</div>}
